### ISSUE TITLE
(=・ω・=) 有哪位大佬用了的可以吱一声吗！

### ISSUE THREAD

**Issue by echisan** [echisan/wbp4j#10]

**Comment by lkshuihua** [comment]
心血来潮用大佬的库做了右击属性可以上传到微博图床,写入到粘贴板,方便写Markdown
[使用图像1](https://ws4.sinaimg.cn/large/007JVmUOgy1g2bfn1xgksj30h30iv75i.jpg)
[使用图像2](https://ws3.sinaimg.cn/large/007JVmUOgy1g2bfre52xzj30xk0gbmzr.jpg)
有个不知道是bug,还是我文档看的不明白,原谅我是java新手,大佬能告诉我您的联系方式吗
```
UploadRequestBuilder.custom("your username", "your password")
                .setCacheFilename("C:/Users/jining/.weibo/wbpcookie")
```
明明上面设置了还是不会去` C:/Users/jining/.weibo/wbpcookie`创建cache文件,因为我是 cmd jar -jar myJar 命令运行我的程序,不是web环境每次我运行都重新建立wbpcookie文件在我打开cmd的地方,不在自定义路径创建,貌似没有用

我的解决方案直接clone你的代码改了源代码,再打包引入我的项目,请问大佬这怎么回事啊
```
public class FileCookieCacheAccessor implements CookieCacheAccessor {
    private static final Logger logger = LoggerFactory.getLogger(FileCookieCacheAccessor.class);
    /**
     * 默认的缓存文件名称，其实也可以是路径，但要符合对应操作系统的路径格式
     */
    private static final String DEFAULT_CACHE_FILE_NAME = "C:/Users/jining/.weibo/wbpcookie";
```

**Comment by echisan** [comment]
@lkshuihua 可以加我qq聊聊，1916152345
应该是个bug，我去测试看看

**Comment by lkshuihua** [comment]
小心翼翼的加了大佬的qq
