### ISSUE TITLE
这个图片上传到哪里了

### ISSUE THREAD

**Issue by zhaop33** [echisan/wbp4j#14]
你好，这个图片上传到哪里了，我上传成功后在微博图片管理中没有看到图片，返回的url可以打开，并且，我将用户名密码写错也能上传成功，可以说明一下吗？

**Comment by echisan** [comment]
1. 图片上传到微博的服务器，为什么再微博图片管理中没看到图片可以看[这里](https://www.jianshu.com/p/55fd50f289c3)，这是微博图床的原理
2. 需要登陆是因为调用微博上传图片的接口需要已登陆用户的cookie
3. 用户名密码写错也能上传成功是因为你上一次登陆成功后已经把cookie缓存到本地了，后来你把用户名写错了也能上传成功是因为检测到本地有缓存就不再登陆了
