### ISSUE TITLE
关于在liunx上调用该组件报错问题

### ISSUE THREAD

**Issue by hackxhao** [echisan/wbp4j#3]
在我当前本地运行时可以正常登陆并获取到cookie，部署到liunx上就出现了以下异常情况：
`com.github.echisan.wbp4j.exception.LoginFailedException: cookie`，麻烦帮忙看下是什么情况导致的

**Comment by echisan** [comment]
你可以测试下在本地linux环境下看看能不能成功获取cookie😂 
不过不行那可能就是我代码的问题了，具体原因的话我也不清楚了（最近比较忙，已经删库跑路了
可以clone下来自己调试一下，还有一个问题参考下 #1 
如果不介意的话欢迎pr或者你自己可以参考下本项目一些登陆的步骤自己实现该库，然后我去star一下w

**Comment by hackxhao** [comment]
@echisan 好的，谢谢。

**Comment by echisan** [comment]
@hackxhao 已修复
