### ISSUE TITLE
com.github.echisan.wbp4j.exception.LoginFailedException: 登陆失败，无法获取cookie

### ISSUE THREAD

**Issue by zplswf** [echisan/wbp4j#4]
你好,在linux报这个错误,该怎么解决?

**Comment by zplswf** [comment]
###[](url)
window可以获取cookie，linux生产环境就无法获取
![22](https://user-images.githubusercontent.com/3021001/52846146-d05f7f00-3143-11e9-8a7d-470f90ce1eb1.png)

**Comment by echisan** [comment]
似乎在云服务器上登陆需要验证码（

**Comment by zplswf** [comment]
> 似乎在云服务器上登陆需要验证码（
那就坑了

**Comment by echisan** [comment]
@zplswf 已修复

**Comment by zplswf** [comment]
你好,修改了什么地方,可否指出下,谢谢！

**Comment by echisan** [comment]
@zplswf 换了种登陆方式 [SzvoneLoginRequest.java](https://github.com/echisan/wbp4j/blob/master/src/main/java/com/github/echisan/wbp4j/SzvoneLoginRequest.java)
