### ISSUE TITLE
解决 cookies 第二次读取失败的

### ISSUE THREAD

**Issue by dong4j** [echisan/wbp4j#5]
兄弟 这么改, 原因注释上已经写了

![image](https://user-images.githubusercontent.com/20341123/54442654-ff383780-4779-11e9-9252-2a98d56f8b87.png)

**Comment by dong4j** [comment]
标题错了 不是第二次读取失败, 是要请求2次才能正确读取 cookies

**Comment by echisan** [comment]
学习了，谢谢老哥， 谢谢pr。不过后面我也有在想，其实直接new File("cookieCache").createNewFile()感觉好像也可以，只要在相对位置就可以了，似乎也可以不要classLoader的感觉
